<?php


namespace App\Repository;


use Doctrine\ORM\EntityRepository;

/**
 * InformeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformeRepository extends EntityRepository
{
    public function findOneByAnio($anio, $academico)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT i FROM App:Informe i
                    JOIN i.academico a
                    WHERE a.id = :academico
                    AND i.anio = :anio"
            )
            ->setParameter('academico', $academico)
            ->setParameter('anio', $anio)
            ->getSingleResult();
    }

    public function findByActivo($anio)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT i FROM App:Informe i
                    JOIN i.academico a
                    WHERE a.activo = :activo
                    AND i.anio = :anio
                    ORDER BY a.apellido ASC"
            )
            ->setParameter('activo', true)
            ->setParameter('anio', $anio)
            ->getResult();
    }
}